services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: GymFlexUser
      POSTGRES_PASSWORD: GymFlexPassword
      POSTGRES_DB: GymFlexDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
